import type { InsertJob } from "@shared/schema";

export const jobDatabase: InsertJob[] = [
  // Senior Level Positions
  {
    title: "Senior Full Stack Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    workType: "Remote",
    experienceLevel: "Senior Level",
    salaryMin: 120000,
    salaryMax: 180000,
    description: "We are looking for a Senior Full Stack Developer to join our growing team. You will be responsible for developing and maintaining web applications using modern technologies.",
    requirements: "5+ years of experience in full-stack development, proficiency in React, Node.js, and database technologies. Strong problem-solving skills and ability to work in an agile environment.",
    skills: ["React", "Node.js", "Python", "JavaScript", "PostgreSQL", "AWS", "Git"],
    postedDate: "2024-06-18",
    companyLogo: "TC"
  },
  {
    title: "Frontend Developer",
    company: "DataSoft Solutions",
    location: "Austin, TX",
    workType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryMin: 95000,
    salaryMax: 130000,
    description: "Join our frontend team to build beautiful and responsive user interfaces. You'll work closely with designers and backend developers to create exceptional user experiences.",
    requirements: "3+ years of frontend development experience, expertise in Vue.js or React, knowledge of TypeScript and modern CSS frameworks.",
    skills: ["Vue.js", "TypeScript", "CSS", "JavaScript", "Sass", "Webpack", "Jest"],
    postedDate: "2024-06-13",
    companyLogo: "DS"
  },
  {
    title: "Machine Learning Engineer",
    company: "AI Innovations Lab",
    location: "Seattle, WA",
    workType: "Remote",
    experienceLevel: "Senior Level",
    salaryMin: 140000,
    salaryMax: 200000,
    description: "Build and deploy machine learning models at scale. Work on cutting-edge AI technologies and help shape the future of artificial intelligence.",
    requirements: "4+ years of ML experience, proficiency in Python, TensorFlow/PyTorch, experience with cloud platforms and MLOps practices.",
    skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "AWS", "Docker", "Kubernetes"],
    postedDate: "2024-06-17",
    companyLogo: "AI"
  },
  {
    title: "DevOps Engineer",
    company: "CloudScale Systems",
    location: "Denver, CO",
    workType: "Remote",
    experienceLevel: "Mid-Level",
    salaryMin: 110000,
    salaryMax: 160000,
    description: "Manage and optimize cloud infrastructure, implement CI/CD pipelines, and ensure high availability of our systems.",
    requirements: "3+ years of DevOps experience, expertise in AWS/Azure, Docker, Kubernetes, and infrastructure as code tools.",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins", "Python", "Bash"],
    postedDate: "2024-06-15",
    companyLogo: "CS"
  },
  {
    title: "Junior Software Developer",
    company: "NextGen Startup",
    location: "Boston, MA",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 70000,
    salaryMax: 95000,
    description: "Start your career with us! Learn and grow while working on exciting projects with modern technologies.",
    requirements: "0-2 years of experience, knowledge of JavaScript, React, and basic backend technologies. Eagerness to learn and grow.",
    skills: ["JavaScript", "React", "MongoDB", "Node.js", "HTML", "CSS", "Git"],
    postedDate: "2024-06-19",
    companyLogo: "NS"
  },
  {
    title: "Data Scientist",
    company: "Analytics Pro",
    location: "New York, NY",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 115000,
    salaryMax: 150000,
    description: "Analyze large datasets, build predictive models, and generate insights to drive business decisions.",
    requirements: "3+ years of data science experience, proficiency in Python, R, SQL, and machine learning frameworks.",
    skills: ["Python", "R", "SQL", "Pandas", "Scikit-learn", "Tableau", "Statistics"],
    postedDate: "2024-06-16",
    companyLogo: "AP"
  },
  {
    title: "Backend Developer",
    company: "Microservices Inc.",
    location: "Chicago, IL",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 100000,
    salaryMax: 140000,
    description: "Design and implement scalable backend services and APIs. Work with microservices architecture and cloud technologies.",
    requirements: "3+ years of backend development, experience with Java or Python, knowledge of microservices patterns and databases.",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Redis", "Docker", "REST APIs", "Microservices"],
    postedDate: "2024-06-14",
    companyLogo: "MI"
  },
  {
    title: "Mobile App Developer",
    company: "AppCraft Studios",
    location: "Los Angeles, CA",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 105000,
    salaryMax: 145000,
    description: "Develop cross-platform mobile applications using React Native. Create smooth and engaging mobile experiences.",
    requirements: "3+ years of mobile development experience, proficiency in React Native, knowledge of iOS/Android platforms.",
    skills: ["React Native", "JavaScript", "iOS", "Android", "Redux", "Firebase", "TypeScript"],
    postedDate: "2024-06-12",
    companyLogo: "AC"
  },
  {
    title: "QA Engineer",
    company: "QualityFirst Tech",
    location: "Portland, OR",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 85000,
    salaryMax: 115000,
    description: "Ensure software quality through comprehensive testing strategies, automation, and quality assurance processes.",
    requirements: "2+ years of QA experience, knowledge of testing frameworks, automation tools, and SDLC processes.",
    skills: ["Selenium", "Jest", "Cypress", "JavaScript", "Testing", "Automation", "JIRA"],
    postedDate: "2024-06-11",
    companyLogo: "QF"
  },
  {
    title: "UI/UX Developer",
    company: "Design Forward",
    location: "Miami, FL",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 90000,
    salaryMax: 125000,
    description: "Bridge the gap between design and development. Implement pixel-perfect UIs and enhance user experiences.",
    requirements: "3+ years of UI development experience, strong CSS skills, knowledge of design tools and frontend frameworks.",
    skills: ["CSS", "JavaScript", "React", "Figma", "Sass", "Animation", "Responsive Design"],
    postedDate: "2024-06-10",
    companyLogo: "DF"
  },
  
  // Additional Senior Level Positions
  {
    title: "Senior Software Architect",
    company: "CloudScale Systems",
    location: "Seattle, WA",
    workType: "Remote",
    experienceLevel: "Senior Level",
    salaryMin: 150000,
    salaryMax: 220000,
    description: "Design and implement large-scale distributed systems. Lead architectural decisions and mentor development teams.",
    requirements: "8+ years of software engineering experience, expertise in system design, microservices, and cloud platforms.",
    skills: ["System Design", "Microservices", "AWS", "Kubernetes", "Java", "Python", "Architecture"],
    postedDate: "2024-06-17",
    companyLogo: "CS"
  },
  {
    title: "Principal Data Engineer",
    company: "DataFlow Technologies",
    location: "Austin, TX",
    workType: "Hybrid",
    experienceLevel: "Senior Level",
    salaryMin: 140000,
    salaryMax: 200000,
    description: "Build and maintain large-scale data pipelines and infrastructure. Lead data engineering initiatives across the organization.",
    requirements: "6+ years in data engineering, expertise in Apache Spark, Kafka, and cloud data platforms.",
    skills: ["Apache Spark", "Kafka", "Python", "SQL", "AWS", "Databricks", "ETL"],
    postedDate: "2024-06-16",
    companyLogo: "DT"
  },
  {
    title: "Senior iOS Engineer",
    company: "MobileFirst Inc",
    location: "San Francisco, CA",
    workType: "Full-time",
    experienceLevel: "Senior Level",
    salaryMin: 130000,
    salaryMax: 190000,
    description: "Lead iOS development for our flagship mobile application. Work on cutting-edge features and performance optimization.",
    requirements: "5+ years iOS development, expertise in Swift, SwiftUI, and iOS frameworks. Experience with large-scale consumer apps.",
    skills: ["Swift", "SwiftUI", "iOS", "Xcode", "Core Data", "UIKit", "Objective-C"],
    postedDate: "2024-06-15",
    companyLogo: "MF"
  },
  {
    title: "Senior Security Engineer",
    company: "CyberShield Corp",
    location: "Washington, DC",
    workType: "Full-time",
    experienceLevel: "Senior Level",
    salaryMin: 135000,
    salaryMax: 185000,
    description: "Protect our infrastructure and applications from security threats. Implement security best practices and conduct security audits.",
    requirements: "5+ years in cybersecurity, knowledge of penetration testing, security frameworks, and compliance standards.",
    skills: ["Penetration Testing", "Security Auditing", "Python", "Network Security", "CISSP", "AWS Security", "Compliance"],
    postedDate: "2024-06-14",
    companyLogo: "CC"
  },
  
  // Leadership Positions
  {
    title: "Engineering Manager",
    company: "Scale Ventures",
    location: "New York, NY",
    workType: "Full-time",
    experienceLevel: "Leadership",
    salaryMin: 160000,
    salaryMax: 230000,
    description: "Lead a team of 8-12 engineers building next-generation fintech products. Drive technical strategy and team development.",
    requirements: "3+ years of engineering management experience, strong technical background, experience in agile methodologies.",
    skills: ["Team Leadership", "Agile", "Software Architecture", "Performance Management", "Strategy", "Mentoring", "Fintech"],
    postedDate: "2024-06-13",
    companyLogo: "SV"
  },
  {
    title: "VP of Engineering",
    company: "GrowthTech Solutions",
    location: "San Francisco, CA",
    workType: "Full-time",
    experienceLevel: "Leadership",
    salaryMin: 200000,
    salaryMax: 300000,
    description: "Lead engineering organization of 50+ engineers. Drive technical vision, scalability, and engineering culture.",
    requirements: "8+ years of engineering leadership experience, proven track record of scaling engineering teams and products.",
    skills: ["Executive Leadership", "Scaling Teams", "Technical Strategy", "Product Development", "Engineering Culture", "Budget Management", "Board Reporting"],
    postedDate: "2024-06-12",
    companyLogo: "GT"
  },
  {
    title: "CTO",
    company: "InnovateLabs",
    location: "Austin, TX",
    workType: "Full-time",
    experienceLevel: "Leadership",
    salaryMin: 250000,
    salaryMax: 350000,
    description: "Lead technology strategy for a fast-growing startup. Build engineering organization from ground up and drive product innovation.",
    requirements: "10+ years of technology leadership, startup experience, expertise in building scalable technology platforms.",
    skills: ["Technology Strategy", "Startup Leadership", "Product Innovation", "Team Building", "Fundraising", "Board Management", "Vision Setting"],
    postedDate: "2024-06-11",
    companyLogo: "IL"
  },
  {
    title: "Director of Product Engineering",
    company: "ProductFirst Technologies",
    location: "Seattle, WA",
    workType: "Hybrid",
    experienceLevel: "Leadership",
    salaryMin: 180000,
    salaryMax: 250000,
    description: "Bridge product and engineering teams. Lead cross-functional initiatives and drive product-engineering alignment.",
    requirements: "6+ years of product engineering leadership, experience in product management and engineering management.",
    skills: ["Product Management", "Engineering Leadership", "Cross-functional Collaboration", "Product Strategy", "Technical Program Management", "Stakeholder Management", "Data-driven Decision Making"],
    postedDate: "2024-06-10",
    companyLogo: "PT"
  },
  
  // Mid-Level Positions
  {
    title: "Full Stack Engineer",
    company: "WebWorks Studio",
    location: "Portland, OR",
    workType: "Remote",
    experienceLevel: "Mid-Level",
    salaryMin: 95000,
    salaryMax: 135000,
    description: "Build modern web applications using React and Node.js. Work on both frontend and backend features.",
    requirements: "3+ years of full-stack development, proficiency in React, Node.js, and database technologies.",
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "Express", "REST APIs", "Git"],
    postedDate: "2024-06-09",
    companyLogo: "WS"
  },
  {
    title: "Platform Engineer",
    company: "CloudNative Systems",
    location: "Denver, CO",
    workType: "Remote",
    experienceLevel: "Mid-Level",
    salaryMin: 105000,
    salaryMax: 145000,
    description: "Build and maintain developer platforms and infrastructure. Focus on automation, monitoring, and developer experience.",
    requirements: "3+ years of platform/infrastructure experience, knowledge of Kubernetes, CI/CD, and cloud platforms.",
    skills: ["Kubernetes", "Docker", "Terraform", "CI/CD", "Monitoring", "Infrastructure as Code", "DevOps"],
    postedDate: "2024-06-08",
    companyLogo: "CN"
  },
  {
    title: "Software Engineer II",
    company: "Enterprise Solutions Inc",
    location: "Chicago, IL",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 100000,
    salaryMax: 140000,
    description: "Develop enterprise software solutions using Java and Spring framework. Work on complex business logic and integrations.",
    requirements: "3+ years of Java development, experience with Spring framework, understanding of enterprise patterns.",
    skills: ["Java", "Spring Boot", "Hibernate", "PostgreSQL", "Maven", "JUnit", "Enterprise Architecture"],
    postedDate: "2024-06-07",
    companyLogo: "ES"
  },
  {
    title: "React Developer",
    company: "Frontend Specialists",
    location: "Remote",
    workType: "Remote",
    experienceLevel: "Mid-Level",
    salaryMin: 90000,
    salaryMax: 125000,
    description: "Build responsive and interactive user interfaces using React. Focus on performance optimization and user experience.",
    requirements: "3+ years of React development, knowledge of modern JavaScript, experience with state management libraries.",
    skills: ["React", "JavaScript", "Redux", "CSS", "HTML", "Webpack", "Testing"],
    postedDate: "2024-06-06",
    companyLogo: "FS"
  },
  {
    title: "Python Backend Developer",
    company: "API Gateway Corp",
    location: "Boston, MA",
    workType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryMin: 95000,
    salaryMax: 130000,
    description: "Build scalable backend services and APIs using Python. Work on microservices architecture and database optimization.",
    requirements: "3+ years of Python development, experience with Django or FastAPI, knowledge of database design.",
    skills: ["Python", "Django", "FastAPI", "PostgreSQL", "Redis", "Docker", "API Development"],
    postedDate: "2024-06-05",
    companyLogo: "AG"
  },
  
  // Entry Level Positions
  {
    title: "Junior Frontend Developer",
    company: "StartupHub",
    location: "Austin, TX",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 65000,
    salaryMax: 85000,
    description: "Learn and grow as a frontend developer. Work on modern web applications using React and TypeScript.",
    requirements: "0-2 years of experience, knowledge of JavaScript, HTML, CSS. Eagerness to learn and grow.",
    skills: ["JavaScript", "HTML", "CSS", "React", "TypeScript", "Git", "Responsive Design"],
    postedDate: "2024-06-04",
    companyLogo: "SH"
  },
  {
    title: "Associate Software Engineer",
    company: "TechFoundation",
    location: "San Diego, CA",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 70000,
    salaryMax: 90000,
    description: "Start your career in software engineering. Work on various projects and learn from experienced developers.",
    requirements: "Computer Science degree or equivalent experience, basic programming knowledge, problem-solving skills.",
    skills: ["Java", "Python", "JavaScript", "SQL", "Git", "Algorithms", "Data Structures"],
    postedDate: "2024-06-03",
    companyLogo: "TF"
  },
  {
    title: "Junior Data Analyst",
    company: "DataInsights Co",
    location: "Remote",
    workType: "Remote",
    experienceLevel: "Entry Level",
    salaryMin: 60000,
    salaryMax: 80000,
    description: "Analyze data to provide business insights. Learn data analysis tools and statistical methods.",
    requirements: "Bachelor's degree in relevant field, basic knowledge of SQL and Excel, analytical mindset.",
    skills: ["SQL", "Excel", "Python", "Statistics", "Data Visualization", "Tableau", "R"],
    postedDate: "2024-06-02",
    companyLogo: "DI"
  },
  {
    title: "Web Developer Trainee",
    company: "DigitalCraft Academy",
    location: "Phoenix, AZ",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 55000,
    salaryMax: 75000,
    description: "Learn web development through hands-on projects. Receive mentoring and training in modern web technologies.",
    requirements: "Basic knowledge of HTML, CSS, and JavaScript. Strong willingness to learn and commitment to growth.",
    skills: ["HTML", "CSS", "JavaScript", "WordPress", "Basic PHP", "Git", "Web Design"],
    postedDate: "2024-06-01",
    companyLogo: "DC"
  },
  {
    title: "QA Engineer Intern",
    company: "QualityFirst Software",
    location: "Minneapolis, MN",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 50000,
    salaryMax: 70000,
    description: "Learn software testing methodologies and quality assurance processes. Work with automated testing tools.",
    requirements: "Recent graduate or final year student, basic understanding of software development lifecycle.",
    skills: ["Manual Testing", "Test Cases", "Bug Tracking", "Selenium", "Basic Programming", "SDLC", "Attention to Detail"],
    postedDate: "2024-05-31",
    companyLogo: "QS"
  },

  // More Specialized Senior Positions
  {
    title: "Staff Software Engineer",
    company: "TechScale Inc",
    location: "Palo Alto, CA",
    workType: "Full-time",
    experienceLevel: "Senior Level",
    salaryMin: 180000,
    salaryMax: 250000,
    description: "Lead technical initiatives across multiple teams. Design and implement complex distributed systems at scale.",
    requirements: "8+ years of software engineering, experience leading technical projects, expertise in distributed systems.",
    skills: ["Distributed Systems", "System Design", "Technical Leadership", "Mentoring", "Go", "Kubernetes", "Microservices"],
    postedDate: "2024-05-30",
    companyLogo: "TS"
  },
  {
    title: "Senior AI/ML Engineer",
    company: "Neural Networks Corp",
    location: "Mountain View, CA",
    workType: "Remote",
    experienceLevel: "Senior Level",
    salaryMin: 160000,
    salaryMax: 220000,
    description: "Build and deploy machine learning models for production systems. Work on cutting-edge AI applications.",
    requirements: "5+ years in machine learning, PhD preferred, experience with deep learning frameworks and MLOps.",
    skills: ["Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "MLOps", "Python", "Statistics"],
    postedDate: "2024-05-29",
    companyLogo: "NN"
  },
  {
    title: "Senior DevOps Architect",
    company: "Infrastructure Masters",
    location: "Seattle, WA",
    workType: "Hybrid",
    experienceLevel: "Senior Level",
    salaryMin: 145000,
    salaryMax: 200000,
    description: "Design and implement cloud infrastructure solutions. Lead DevOps transformation initiatives.",
    requirements: "6+ years DevOps experience, expertise in cloud platforms, infrastructure automation, and CI/CD.",
    skills: ["AWS", "Terraform", "Kubernetes", "Docker", "Jenkins", "Infrastructure as Code", "Monitoring"],
    postedDate: "2024-05-28",
    companyLogo: "IM"
  },
  {
    title: "Senior Frontend Architect",
    company: "UI Excellence Lab",
    location: "Los Angeles, CA",
    workType: "Full-time",
    experienceLevel: "Senior Level",
    salaryMin: 130000,
    salaryMax: 180000,
    description: "Lead frontend architecture decisions and mentor frontend developers. Build scalable component libraries.",
    requirements: "6+ years frontend development, expertise in React ecosystem, experience with design systems.",
    skills: ["React", "TypeScript", "Component Libraries", "Design Systems", "Performance Optimization", "Webpack", "Testing"],
    postedDate: "2024-05-27",
    companyLogo: "UE"
  },
  {
    title: "Senior Database Engineer",
    company: "DataPlatform Solutions",
    location: "Chicago, IL",
    workType: "Remote",
    experienceLevel: "Senior Level",
    salaryMin: 125000,
    salaryMax: 175000,
    description: "Design and optimize database systems. Ensure high availability and performance of data infrastructure.",
    requirements: "5+ years database engineering, expertise in PostgreSQL, MySQL, performance tuning, and backup strategies.",
    skills: ["PostgreSQL", "MySQL", "Database Design", "Performance Tuning", "Replication", "Backup and Recovery", "SQL"],
    postedDate: "2024-05-26",
    companyLogo: "DP"
  },

  // Additional Mid-Level Positions
  {
    title: "Android Developer",
    company: "Mobile Innovation Studio",
    location: "San Diego, CA",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 100000,
    salaryMax: 140000,
    description: "Develop native Android applications using Kotlin. Work on consumer-facing mobile apps with millions of users.",
    requirements: "3+ years Android development, proficiency in Kotlin, experience with Android SDK and modern architecture patterns.",
    skills: ["Kotlin", "Android SDK", "MVVM", "Room", "Retrofit", "Jetpack Compose", "Mobile Development"],
    postedDate: "2024-05-25",
    companyLogo: "MI"
  },
  {
    title: "Cloud Engineer",
    company: "CloudFirst Technologies",
    location: "Austin, TX",
    workType: "Remote",
    experienceLevel: "Mid-Level",
    salaryMin: 105000,
    salaryMax: 145000,
    description: "Build and maintain cloud infrastructure on AWS. Implement automation and monitoring solutions.",
    requirements: "3+ years cloud engineering experience, AWS certification preferred, knowledge of infrastructure automation.",
    skills: ["AWS", "CloudFormation", "Lambda", "EC2", "S3", "Monitoring", "Security"],
    postedDate: "2024-05-24",
    companyLogo: "CF"
  },
  {
    title: "Node.js Developer",
    company: "Backend Specialists Inc",
    location: "Remote",
    workType: "Remote",
    experienceLevel: "Mid-Level",
    salaryMin: 95000,
    salaryMax: 130000,
    description: "Build scalable backend services using Node.js and Express. Work on API development and microservices.",
    requirements: "3+ years Node.js development, experience with Express, database design, and API development.",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs", "Microservices", "Authentication", "Testing"],
    postedDate: "2024-05-23",
    companyLogo: "BS"
  },
  {
    title: "Vue.js Developer",
    company: "Frontend Dynamics",
    location: "Portland, OR",
    workType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryMin: 90000,
    salaryMax: 125000,
    description: "Develop modern web applications using Vue.js and Nuxt.js. Focus on performance and user experience.",
    requirements: "3+ years Vue.js development, experience with Nuxt.js, understanding of modern JavaScript and CSS.",
    skills: ["Vue.js", "Nuxt.js", "JavaScript", "CSS", "Vuex", "Component Design", "Performance Optimization"],
    postedDate: "2024-05-22",
    companyLogo: "FD"
  },
  {
    title: "Blockchain Developer",
    company: "CryptoTech Solutions",
    location: "Miami, FL",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 110000,
    salaryMax: 150000,
    description: "Develop decentralized applications and smart contracts. Work on blockchain integration and cryptocurrency solutions.",
    requirements: "2+ years blockchain development, experience with Solidity, understanding of DeFi protocols.",
    skills: ["Solidity", "Ethereum", "Smart Contracts", "Web3", "DeFi", "Blockchain", "Cryptography"],
    postedDate: "2024-05-21",
    companyLogo: "CT"
  },

  // Additional Entry Level Positions
  {
    title: "Junior Python Developer",
    company: "CodeAcademy Labs",
    location: "Remote",
    workType: "Remote",
    experienceLevel: "Entry Level",
    salaryMin: 60000,
    salaryMax: 80000,
    description: "Learn Python development while working on real projects. Focus on backend development and data processing.",
    requirements: "Basic Python knowledge, understanding of programming fundamentals, eagerness to learn.",
    skills: ["Python", "Django", "Flask", "SQL", "Git", "Linux", "Problem Solving"],
    postedDate: "2024-05-20",
    companyLogo: "CA"
  },
  {
    title: "Junior Mobile Developer",
    company: "AppStart Studio",
    location: "Denver, CO",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 65000,
    salaryMax: 85000,
    description: "Start your mobile development career. Work on both iOS and Android applications using React Native.",
    requirements: "Basic knowledge of JavaScript and React, understanding of mobile development concepts.",
    skills: ["React Native", "JavaScript", "iOS", "Android", "Mobile UI", "Git", "Debugging"],
    postedDate: "2024-05-19",
    companyLogo: "AS"
  },
  {
    title: "Graduate Software Developer",
    company: "TechGrad Program",
    location: "Boston, MA",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 70000,
    salaryMax: 90000,
    description: "Structured graduate program with rotations across different teams. Learn various technologies and methodologies.",
    requirements: "Recent computer science graduate, strong academic performance, passion for technology.",
    skills: ["Programming Fundamentals", "Software Engineering", "Agile", "Team Collaboration", "Learning Ability", "Problem Solving", "Communication"],
    postedDate: "2024-05-18",
    companyLogo: "TG"
  },
  {
    title: "Junior DevOps Engineer",
    company: "Infrastructure Beginnings",
    location: "Atlanta, GA",
    workType: "Full-time",
    experienceLevel: "Entry Level",
    salaryMin: 65000,
    salaryMax: 85000,
    description: "Learn DevOps practices and cloud technologies. Work with senior engineers on automation and deployment.",
    requirements: "Basic understanding of Linux, interest in automation and cloud technologies, willingness to learn.",
    skills: ["Linux", "Basic Scripting", "Git", "Docker", "AWS Basics", "Automation", "Monitoring"],
    postedDate: "2024-05-17",
    companyLogo: "IB"
  },
  {
    title: "Technical Support Engineer",
    company: "SupportTech Solutions",
    location: "Remote",
    workType: "Remote",
    experienceLevel: "Entry Level",
    salaryMin: 55000,
    salaryMax: 75000,
    description: "Provide technical support to customers and internal teams. Learn troubleshooting and customer communication skills.",
    requirements: "Technical aptitude, strong communication skills, problem-solving ability, customer service orientation.",
    skills: ["Technical Support", "Troubleshooting", "Customer Service", "Documentation", "Basic Programming", "System Administration", "Communication"],
    postedDate: "2024-05-16",
    companyLogo: "ST"
  },

  // Specialized and Niche Positions
  {
    title: "Game Developer",
    company: "Gaming Studio Pro",
    location: "Los Angeles, CA",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 85000,
    salaryMax: 120000,
    description: "Develop video games using Unity and C#. Work on gameplay mechanics, graphics, and performance optimization.",
    requirements: "3+ years game development experience, proficiency in Unity and C#, understanding of game design principles.",
    skills: ["Unity", "C#", "Game Design", "3D Graphics", "Performance Optimization", "Physics", "Animation"],
    postedDate: "2024-05-15",
    companyLogo: "GS"
  },
  {
    title: "Embedded Systems Engineer",
    company: "IoT Innovations Corp",
    location: "San Jose, CA",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 100000,
    salaryMax: 140000,
    description: "Design and develop embedded systems for IoT devices. Work on firmware development and hardware integration.",
    requirements: "3+ years embedded systems experience, proficiency in C/C++, understanding of microcontrollers and electronics.",
    skills: ["C/C++", "Embedded Systems", "Microcontrollers", "RTOS", "Hardware Design", "IoT", "Firmware"],
    postedDate: "2024-05-14",
    companyLogo: "II"
  },
  {
    title: "Salesforce Developer",
    company: "CRM Solutions Expert",
    location: "Dallas, TX",
    workType: "Hybrid",
    experienceLevel: "Mid-Level",
    salaryMin: 95000,
    salaryMax: 130000,
    description: "Customize and develop Salesforce applications. Build custom solutions and integrations for business processes.",
    requirements: "2+ years Salesforce development, Salesforce certifications preferred, knowledge of Apex and Lightning.",
    skills: ["Salesforce", "Apex", "Lightning", "SOQL", "Visualforce", "Process Builder", "Integration"],
    postedDate: "2024-05-13",
    companyLogo: "CS"
  },
  {
    title: "Site Reliability Engineer",
    company: "Reliability First Inc",
    location: "San Francisco, CA",
    workType: "Remote",
    experienceLevel: "Mid-Level",
    salaryMin: 115000,
    salaryMax: 160000,
    description: "Ensure system reliability and performance. Implement monitoring, alerting, and incident response procedures.",
    requirements: "3+ years in SRE or similar role, experience with monitoring tools, understanding of distributed systems.",
    skills: ["SRE", "Monitoring", "Incident Response", "Automation", "Kubernetes", "Observability", "Performance Tuning"],
    postedDate: "2024-05-12",
    companyLogo: "RF"
  },
  {
    title: "ETL Developer",
    company: "Data Pipeline Corp",
    location: "Chicago, IL",
    workType: "Full-time",
    experienceLevel: "Mid-Level",
    salaryMin: 90000,
    salaryMax: 125000,
    description: "Design and implement data extraction, transformation, and loading processes. Work with large datasets and data warehouses.",
    requirements: "3+ years ETL development, experience with data warehousing, proficiency in SQL and scripting languages.",
    skills: ["ETL", "SQL", "Data Warehousing", "Python", "Apache Airflow", "Data Modeling", "Big Data"],
    postedDate: "2024-05-11",
    companyLogo: "DC"
  }
];
